os:
  - linux

sudo: required
dist: trusty

language: node_js
node_js:
  - "4.4"

before_install:
  - sudo apt-get update
  - sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libavahi-compat-libdnssd-dev libavahi-compat-libdnssd-dev

script:
  - npm run test

notifications:
  email: false
