sudo: required
language: node_js
node_js:
  - "4.4"

before_install:
  - sudo apt-get update
  - sudo apt-get install libavahi-compat-libdnssd-dev libavahi-compat-libdnssd-dev
  - if ["$CXX" = "g++"]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

script:
  - npm run test

notifications:
  email: false
