sudo: required
language: node_js
node_js:
  - "4.4"
env:
  - CXX=g++-4.8

before_install:
  - sudo apt-get update
  - sudo apt-get install libavahi-compat-libdnssd-dev libavahi-compat-libdnssd-dev g++-4.8

script:
  # DEV: Currently our test suite runs locally only
  #   This should be resolved in #19
  - npm run test
